"""Initial migration

Revision ID: 524ebcd1ffc0
Revises: 
Create Date: 2024-06-15 22:20:49.415765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524ebcd1ffc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('client_secret', sa.String(length=128), nullable=True),
    sa.Column('client_name', sa.String(length=64), nullable=True),
    sa.Column('redirect_uri', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_client_id'), 'client', ['client_id'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('auth_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('redirect_uri', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_code_code'), 'auth_code', ['code'], unique=True)
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=256), nullable=True),
    sa.Column('refresh_token', sa.String(length=256), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expires_in', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_access_token'), 'token', ['access_token'], unique=True)
    op.create_index(op.f('ix_token_refresh_token'), 'token', ['refresh_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_refresh_token'), table_name='token')
    op.drop_index(op.f('ix_token_access_token'), table_name='token')
    op.drop_table('token')
    op.drop_index(op.f('ix_auth_code_code'), table_name='auth_code')
    op.drop_table('auth_code')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_client_client_id'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
