"""Add avatar and nickname to User

Revision ID: 6ef764c31db7
Revises: c8acd6057aa4
Create Date: 2024-06-15 23:18:33.340252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef764c31db7'
down_revision = 'c8acd6057aa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('nickname', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'nickname')
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
