"""Add email

Revision ID: 703661131508
Revises: 6ef764c31db7
Create Date: 2024-06-16 01:14:23.746537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703661131508'
down_revision = '6ef764c31db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
